class Codekata{isUrlValid(url){return /^(https?|s?ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test(url);}
validateGithubUrl(githuburl,gitLanguage){let submitted_url=githuburl;submitted_url=submitted_url.trim();let valid_url=this.isUrlValid(submitted_url);let userLanguage=gitLanguage.toLowerCase();let fetchExt=submitted_url.split('.');let fileExtension=fetchExt.reverse()[0];let extn_check={"java":"java","java 8":"java","bash":"sh","scala":"scala","go":"go","objective c":"m","c":"c","cpp":"cpp","c++":"cpp","cs":"cs","c#":"cs","csharp":"cs","python":"py","python 2":"py","python 3":"py","py":"py","php":"php","javascript":"js","js":"js","ruby":"rb","clojure":"clj","groovy":"groovy","perl":"pl","lisp":"lsp"};if(!valid_url){return 0;}else if(submitted_url.indexOf("github")==-1){return 1;}else if(extn_check[userLanguage]!=fileExtension){return 3;}else{return 4;}}
fetchQuestion(data,resolve){$("#codeNext").addClass("disabled");let setui=this;let search=new URLSearchParams(document.location.search.substring(1));let concept=search.get("concept");let Qid=authorize.getSession(concept+"currentQid");if(typeof(data.qid)==='undefined'){if((!Qid)&&(typeof Qid!=='undefined')){authorize.ajax(data,"codekataFetchQuestions",function(response){setui.buildAttendedQuestions(response);$("#allQuestionsModal").data("questionData",response);setui.setCodekataQuestion(response,"new");resolve();});}else{let Questions=authorize.getSession(concept+Qid);setui.buildAttendedQuestions(Questions);$("#allQuestionsModal").data("questionData",Questions);this.setCodekataQuestion(Questions,"catch");resolve();}}else{let requestQid=data.qid;authorize.setSession(concept+"currentQid",requestQid);authorize.ajax(data,"codekataFetchQuestions",function(response){setui.buildAttendedQuestions(response);$("#allQuestionsModal").data("questionData",response);setui.setCodekataQuestion(response,"new");resolve();});}};splitupPage(x,y){let xaxis=x;let yaxis=y;Split(['#codeEditorWrap','#outputPanelWrap'],{direction:'vertical',gutterSize:20,sizes:[xaxis,yaxis],gutterAlign:'end',minSize:[90,50],cursor:'pointer',});}
setCodekataQuestion(response,status){$("#codeNext").removeClass("disabled");if(response){let result=JSON.parse(response);if(result.status=="success"){result=JSON.parse(result.questionData);if(!result.paidUser&&result.isLastQuestion){$("#freeUserModal").modal("show");}
let Qid=result.qid;let QuestionOrder=result.questionOrder;let search=new URLSearchParams(document.location.search.substring(1));let concept=search.get("concept");if(status==="new"){if(!Qid){return false;}else{authorize.setSession(concept+Qid,response);authorize.setSession(concept+"currentQid",Qid);authorize.setSession(concept+"order",JSON.stringify(result.questionOrder));}}
let AttendedQuestionLength=parseInt(QuestionOrder.length);let TotalQuestionLength=parseInt(result.totalCount);authorize.setSession(concept+"AttendedQuestionLength",AttendedQuestionLength);authorize.setSession(concept+"TotalQuestionLength",TotalQuestionLength);let cQid=authorize.getSession(concept+"currentQid");let cqOrder=authorize.getSession(concept+"order");let cquestionOrder=JSON.parse(cqOrder);let ccurrentIndex=parseInt(cquestionOrder.indexOf(parseInt(cQid)));let currentQidLength=parseInt(ccurrentIndex+1);if(currentQidLength===TotalQuestionLength){$("#codeSkip,#codeNext").addClass("disabled");}else if(AttendedQuestionLength===TotalQuestionLength){$("#codeSkip").addClass("disabled");}else if(AttendedQuestionLength==1){$("#codePre").addClass("disabled");}
let Questions=result.question;let sampleInput=result.sampleInput?result.sampleInput:"";let sampleOutput=result.sampleOutput?result.sampleOutput:"";let hardnessScore=result.hardnessScore;let explanation=result.explanation;result.inputDescription?$('#inputDescription').html('<p><strong>Input Description:</strong><br> '+result.inputDescription+'</p>'):$('#inputDescription').html("");result.outputDescription?$('#outputDescription').html('<p><strong>Output Description:</strong><br> '+result.outputDescription+'</p>'):$('#outputDescription').html("");sampleInput=authorize.HtmlEntityToStr(sampleInput);sampleOutput=authorize.HtmlEntityToStr(sampleOutput);$("#codeKataQuestions").html(Questions);$(".number-id-wrap").html(decodeURI(concept)+'<span class="number-id ">'+(result.questionOrder.indexOf(Number(result.qid))+1)+'</span>');$('#programExplain').html(explanation);if(sampleInput){$('#sampleInput').html('<pre><strong>Sample Input :</strong><br>'+sampleInput+'</pre>');}
else{$('#sampleInput').html("");}
if(sampleOutput){$('#sampleOutput').html('<pre><strong>Sample Output :</strong><br>'+sampleOutput+'</pre>');}
else{$('#sampleOutput').html("");}}
else if(result.status=="error"){result=JSON.parse(result.questionData);}}else{alert("no Question Found");}}
buildAttendedQuestions(response){try{response=JSON.parse(response);if(response&&response.status=="success"){let questionData=JSON.parse(response.questionData);let attendedMarkup="";let fixedWidth=70;let attendedMarkupId=$("#attendedMarkup");let modalWidth=attendedMarkupId.width();let rowBreak=Math.floor(modalWidth/fixedWidth);let variableRowBreak=rowBreak;let finalMarkUp="";let oddRow=true;let questionOrderLength=questionData.questionOrder.length;for(let itr=0;itr<questionOrderLength;itr++){if(response.completionStatus.completed&&response.completionStatus.completed.includes(questionData.questionOrder[itr].toString())){attendedMarkup+='<div class="question-ball completed-indication d-flex justify-content-center align-items-center"><span class="number-text text-white btn question-number" data-qid="'+questionData.questionOrder[itr]+'">'+(itr+1)+'</span></div>';}
else if(response.completionStatus.notCompleted&&response.completionStatus.notCompleted.includes(questionData.questionOrder[itr].toString())){attendedMarkup+='<div class="question-ball not-completed-indication d-flex justify-content-center align-items-center"><span class="number-text text-white btn question-number" data-qid="'+questionData.questionOrder[itr]+'">'+(itr+1)+'</span></div>';}
else{attendedMarkup+='<div class="question-ball not-attended-indication d-flex justify-content-center align-items-center"><span class="number-text btn question-number" data-qid="'+questionData.questionOrder[itr]+'">'+(itr+1)+'</span></div>';}
if(variableRowBreak===(itr+1)){finalMarkUp+=oddRow?'<div class="row odd-row">'+attendedMarkup+'</div>':'<div class="row flex-row-reverse even-row">'+attendedMarkup+'</div>';if(itr!==questionOrderLength-1){finalMarkUp+=oddRow?'<div class="row odd-path-connector justify-content-end"><div class="path-connector-vertical"></div></div>':'<div class="row even-path-connector"><div class="path-connector-vertical"></div></div>';}
attendedMarkup="";variableRowBreak+=rowBreak;oddRow=oddRow?false:true;}
else if(itr!==questionOrderLength-1){attendedMarkup+='<div class="path-connector align-self-center"></div>';}}
if(attendedMarkup!==""){finalMarkUp+=oddRow?'<div class="row odd-row">'+attendedMarkup+'</div>':'<div class="row flex-row-reverse even-row">'+attendedMarkup+'</div>';}
attendedMarkupId.html(finalMarkUp);let offsetWidth=attendedMarkupId[0].scrollHeight>attendedMarkupId[0].clientHeight?(attendedMarkupId[0].offsetWidth-attendedMarkupId[0].clientWidth):0;$(".even-row").css("margin-right",(modalWidth%fixedWidth)+10-offsetWidth);$(".odd-row").css("margin-left",10);$(".odd-path-connector").css("margin-right",(modalWidth%fixedWidth)+10+25-2.5-offsetWidth);$(".even-path-connector").css("margin-left",10+25-2.5);}}
catch(error){console.log(error);}}
setCodekataCurrentQid(concept,data){let userData=JSON.stringify(data);authorize.setSession(tags+qid,userData);};checkGitUrl(git_url){var url,status;var subUrl=git_url.split("/");var contents=git_url.split("master");var urlLength=subUrl.length;var x;var extn,linecount,user_src;var uname=subUrl[3];var repo=subUrl[4];var content=subUrl[urlLength-1];var check=content.split('.');url="https://api.github.com/repos/"+uname+"/"+repo+"/contents"+contents[1]+""+"?access_token=acbe86fe2ef6e073616c9aa007708891ad15fc24";$.ajax({method:"get",url:url,cache:false,success:function(response){if(response){status=response
var program=response.content;program=atob(program);var line=program.split("\n");var fileExt=content.split('.').pop();var linelength=line.length-1;linecount=linelength;extn=fileExt;user_src=program;status=true;}},error:function(XMLHttpRequest,textStatus,errorThrown){if(textStatus){status=false;}}});}}
$(document).on("hidden.bs.modal","#freeUserModal",function(data){let search=new URLSearchParams(document.location.search.substring(1));let conceptId=search.get("concept");let questionId=authorize.getSession(conceptId+"currentQid");let questionData=authorize.getSession(conceptId+questionId);questionData=JSON.parse(questionData);let trialCount=0;if(questionData&&questionData.questionData!==undefined){questionData=JSON.parse(questionData.questionData);trialCount=questionData.trialCount;}
if(!trialCount){window.location.href="code-kata.html";}});$(document).on("shown.bs.modal","#allQuestionsModal",function(){let data=$(this).data("questionData");let obj=new Codekata();obj.buildAttendedQuestions(data);});