$(document).ready(function(){var obj=new steroid();var json_value={};var img_url;var newurl;var result_clg,flag;json_value['hash']=localStorage.getItem("hash_val");json_value['type']="college";var s3url="https://s3-ap-southeast-1.amazonaws.com/guvi-profile-images/";function render(result){function url_split(image){if(image){img_url=image.split("/");if(img_url[2]!="graph.facebook.com"){var d=img_url.length-1;newurl=s3url+img_url[d];}else{newurl=image;}}
else{newurl="./images/profile-pic-sample.jpeg";}}
for(var i=0;i<3;i++){if(i==0){var class_rank=".first";}
else{class_rank=(i==1)?".second":".third";}
$(class_rank).find("p.leader-name").text(result[i]['sname']);$(class_rank).find("p.leader-institution-name").text(result[i]['clgname']);$(class_rank).find("p.geekoins span").text(result[i]['tp']);url_split(result[i]['picture_url']);$(class_rank).find("img").attr("src",newurl);$(class_rank).find("a").attr("href","./"+result[i]['unique_url']);}
var res=[];for(i=3;i<result.length;i++){url_split(result[i]['picture_url']);var rank=result[i]['rank'];if(json_value['hash']!=result[i]['hash']&&rank<=10){var row='<tr><td class="rank">'+rank+'</th><td class="profile"> <div class="d-flex flex-row mb-2"> <div class="gravatar-wrap mr-2"> <img src="'+newurl+'" class="gravatar" alt=" "> </div><div class="account-info"> <p class="username">'+result[i]['sname']+'</p><p class="user-institute">'+result[i]['clgname']+'</p><div class="score"> <p class="rank"><strong>Rank:</strong><span>'+rank+'</span></p><p class="geekoins"><i class="icon-geekoin" aria-hidden="true">geekoins:</i><span>'+result[i]['tp']+'</span></p></div></div></div></td><td class="geekoins">'+result[i]['tp']+'</td></tr>';res.push(row);}
else if(json_value['hash']==result[i]['hash']){if(result[i]['college_id']==11){$('#btn2').css("display","none");}
if(result[i]['rank']>3){var row='<tr class="bg-primary "><td class="rank ">'+rank+'</th><td class="profile"> <div class="d-flex flex-row mb-2"> <div class="gravatar-wrap mr-2"> <img src="'+newurl+'" class="gravatar" alt="images/acc_icon.png"> </div><div class="account-info"> <p class="username">'+result[i]['sname']+'</p><p class="user-institute">'+result[i]['clgname']+'</p><div class="score"> <p class="rank"><strong>Rank:</strong><span>'+rank+'</span></p><p class="geekoins"><i class="icon-geekoin" aria-hidden="true">geekoins:</i><span>'+result[i]['tp']+'</span></p></div></div></div></td><td class="geekoins">'+result[i]['tp']+'</td></tr>';res.push(row);}}}
$('.leader-board-table').find('tbody').html(res);}
obj.ajax(json_value,'Leaderboard',function(data){result_clg=JSON.parse(data);result_clg['type']="college";if(result_clg[0]['tp']=="no records"){$('#btn2').css("display","none");flag=0;}else{flag=1;}});json_value['type']="overall";obj.ajax(json_value,'Leaderboard',function(data){result_overall=JSON.parse(data);result_overall['type']="overall";render(result_overall);});if(!json_value['hash']){$('#btn2').css("display","none");}
else{$('#switch').on('click',()=>{if($('#switch').prop('checked')){if(flag==1){render(result_clg);}
else{$('#leaderboard').css("display","none");$('#toppers').css("display","none");$('#exception').css("display","");$('#exception').text("NO Codekata records");$('#exception').css("padding","100");$('#exception').css("text-align","center");}}else{render(result_overall);$('#leaderboard').css("display","");$('#toppers').css("display","");$('#exception').css("display","none");}})}})