var queries={};var url;var capchetoken;grecaptcha.ready(function(){grecaptcha.execute("6LdADb4UAAAAAA1feb36sozffPYRKKOqD9WPbibp",{action:"register"}).then(function(token){capchetoken=token;});});$(window).scroll(function(){if($(this).scrollTop()>150)
{$('.mobile-buy').show();}
else
{$('.mobile-buy').hide();}});class CourseBundle{renderCustomVideo(selector,source){try{let videoExtention="mp4";customPlayer.source={type:'video',title:"Deep Learning",sources:[{src:source,type:'video/'+videoExtention}]};customPlayer.play();$(".plyr--full-ui").addClass("embed-responsive-item");$(".plyr__video-wrapper").addClass("embed-responsive-item");$("video").addClass("embed-responsive-item");}
catch(error){console.log(error);}}
setRating(){const stars='.star-ratings-css';const starSetter='.star-ratings-css-top';$(stars).each((idx,star)=>{const rating=$(star).data('rating');const max=$(star).data('max');const width=`${(rating/max)*100}%`;$(star).find(starSetter).css('width',width);});}
decideUser(data){try{if(data.status=="error"){throw data.message;}
$(".custom-radio").prop("hidden",false);if(data.userExists){$("#password").prop("hidden",false);$("#userMessage").prop("hidden",false);$("#nonUserMessage").prop("hidden",true);$("#confirmPassword").prop("hidden",true);}
else{$("#password").prop("hidden",false);$("#userMessage").prop("hidden",true);$("#confirmPassword").prop("hidden",false);$("#nonUserMessage").prop("hidden",false);}
$("#userEmail").data("registeredUser",data.userExists);}
catch(error){console.log(error);}}
validateField(selector){try{let value=$(selector).val();if(!value){$(selector).addClass("is-invalid");$("#userEmail").data("allFieldValidated",false);}
else if(selector=="#userMobile"){let valid=/[0-9 -()+]{10}$/.test(value);if(!valid){$(selector).addClass("is-invalid");$("#").data("allFieldValidated",false);}
else{$(selector).removeClass("is-invalid");}}
else if(selector=="#userEmail"){let valid=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(value);if(!valid){$(selector).addClass("is-invalid");$("#userEmail").data("allFieldValidated",false);}
else{$(selector).removeClass("is-invalid");$("#userEmail").data("allFieldValidated",true);}}
else{$(selector).removeClass("is-invalid");}}
catch(error){console.log(error);}}
hideProp(selector){$(selector).prop("hidden",true);}
showProp(selector){$(selector).prop("hidden",false);}
removeRequired(selector){$(selector).prop("required",false);}
loggedInState(){$("#userEmail").data("loggedState",true);$(".custom-radio").prop("hidden",false);this.hideProp("#password");this.hideProp("#userMessage");if(authorize.getSession("userAuth")){$("#accountGroup").hide();}}
calculateOfferPeriod(){try{let currentTimeStamp=new Date().getTime();let repeatDays=1;let tomorrowTimeStamp=currentTimeStamp+(24*repeatDays*60*60*1000);let tomorrowDate=new Date(tomorrowTimeStamp).getDate();let tomorrowMonth=new Date(tomorrowTimeStamp).getMonth();let tomorrowYear=new Date(tomorrowTimeStamp).getFullYear();let tomorrowMorningTimeStamp=new Date(tomorrowYear,tomorrowMonth,tomorrowDate).getTime();let remainingSeconds=(1584340200000-currentTimeStamp)/1000;let offerTime=this.secondsToHMS(remainingSeconds);$("#offerDate").html("The offer is valid only till "+new Date().getDate()+" "+new Date().toLocaleString("default",{month:"long"}));return offerTime;}
catch(error){console.log(error);}}
renderOfferPeriod(){try{let offerPeroidMarkup=$("#offerPeriod");let classObj=this;setInterval(function(){let offerTime=classObj.calculateOfferPeriod();offerPeroidMarkup.html("Starts in "+offerTime);},1000);}
catch(error){console.log(error);}}
secondsToHMS(remainingTime){remainingTime=parseInt(remainingTime);let days=Math.floor(remainingTime/(3600*24));let hours=Math.floor(remainingTime%(3600*24)/3600);let minutes=Math.floor(remainingTime%3600/60);let seconds=Math.floor(remainingTime%3600%60);return('0'+days).slice(-2)+"d "+('0'+hours).slice(-2)+"h "+('0'+minutes).slice(-2)+"m "+('0'+seconds).slice(-2)+"s";}}
const sidebar=(function sidebar(){const menuList='#sidebar';const toggleicon='#sidebarToggle .material-icons';const collapseClass='sidebar-collapse';const activeClass='active';const EventMenuOpened='shown.bs.collapse';const EventMenuClosed='hidden.bs.collapse';function handleMobileUI(){$(menuList).on(EventMenuClosed,()=>$(toggleicon).html('menu'));$(menuList).on(EventMenuOpened,()=>$(toggleicon).html('close'));}
function toggleSidebar(){$(menuList).hover(()=>$(menuList).toggleClass(collapseClass));}
const init=()=>{handleMobileUI();toggleSidebar();};return{init};}());const coursesProductPage=(function coursesProductPage(){const pageEl='#courses-product-page';const isFunction=functionToCheck=>(functionToCheck&&{}.toString.call(functionToCheck)==='[object Function]');const finishLoading=(pageEl,cb)=>{$('.spinner').hide();$(pageEl).removeClass('loading');return isFunction(cb)?cb():false;};const init=()=>{const thisPage=($(pageEl).length!==0);if(!thisPage){return;}
sidebar.init();finishLoading(pageEl);};return{init,};}());var applyCoupon=0;$(document).ready(function(){authorize.loginCheck();window.onscroll=function(){myFunction()};var navbar=document.getElementById("navbar");var sticky=navbar.offsetTop;function myFunction(){if(window.pageYOffset>=sticky){navbar.classList.add("sticky")}else{navbar.classList.remove("sticky");}}
let obj=new CourseBundle();obj.renderOfferPeriod();let currentdate=new Date().getDate();$("#todaydate").text(currentdate);let emailDomId=$("#userEmail");emailDomId.data("validated",false);emailDomId.data("registeredUser",false);var courses=["pygame_english"];let requestData={type:"coursePack",courseId:courses};authorize.ajax(requestData,"coursePack",function(data){data=JSON.parse(data);if(data["international"]){$(".usd-price").show();$(".price-wrap .price").hide();$(".local").hide();}
function renderCourseDetail(data,key){var arrayBeginner=[],arrayIntermediate=[],arrayAdvanced=[],arrayExpert=[];console.log(data);for(var i=1;i<data.length;i++){if(data[i][1]=="l1")arrayBeginner+="<li><a>"+data[i][0]+"</a></li>";if(data[i][1]=="l2")arrayIntermediate+="<li><a>"+data[i][0]+"</a></li>";if(data[i][1]=="l3")arrayAdvanced+="<li><a>"+data[i][0]+"</a></li>";if(data[i][1]=="l4")arrayExpert+="<li><a>"+data[i][0]+"</a></li>";}
key="."+key;$(key).append(arrayBeginner);$(key).append(arrayIntermediate);$(key).append(arrayAdvanced);$(key).append(arrayExpert);$(key+"_lesson_count").html(data.length-1+" Exclusive Lessons");}
for(var i=0;i<courses.length;i++){renderCourseDetail(data[courses[i]],courses[i]);}});const stars='.star-ratings-css';const starSetter='.star-ratings-css-top';$(stars).each((idx,star)=>{const rating=$(star).data('rating');const max=$(star).data('max');const width=`${(rating/max)*100}%`;$(star).find(starSetter).css('width',width);});let authToken=authorize.getSession("authToken");if(authToken||authorize.getSession("userAuth")){obj.loggedInState();}
else{emailDomId.data("loggedState",false);}
$.each(window.location.search.substr(1).split('&'),function(c,q){var i=q.split('=');queries[i[0].toString()]=i[1];});url=window.location.href;coursesProductPage.init();let search=new URLSearchParams(document.location.search.substring(1));let courseId=search.get("course");var userType=2;if(authorize.getSession("authToken")==null){$("#emailInput").on('focusout',function(){let email=authorize.validate("#emailInput","email");if(email){authorize.ajax({requestType:"mail_check",email:email},"registerCheck",function(response){userType=JSON.parse(response)["user"];$("#passField").css("display","block");if(!userType){$("#confirmPassword").css("display","block");}});}});}else{let obj={};authorize.ajax({requestType:"loggedIn"},"registerCheck",function(response){response=JSON.parse(response);$("#paymentbtn").data("profileData",response);authorize.setSession("email",response["email"]);authorize.setSession("mobile",response["mobile"]);if(response["passedoutyear"]!="-select-"&&response["passedoutyear"]){authorize.setSession("passedoutyear",response["passedoutyear"]);}
if(response["department"]!="-select-"&&response["department"]){authorize.setSession("department",response["department"]);}
$("#userEmail").val(response["email"]);$("#userEmail").attr("disabled","true");$("#userName").val(response["firstName"]);$("#userName").attr("disabled","true");$("#userEmail").data("loggedState",true);$("#password").prop("hidden",true);$("#confirmPassword").prop("hidden",true);});}});$(document).on("click","#try-codekata",function(data){window.location.href="code-kata.html";});$(document).on("input change","#emailInput",function(data){$("#passField").css("display","none");$("#confirmPassField").css("display","none");});$(document).on("click","#applyCoupon",function(data){applyCoupon=$("#applyCoupon").hasClass("apply");if(applyCoupon){$("#applyCoupon").removeClass("apply");$("#applyCoupon").addClass("remove");}else{$("#applyCoupon").removeClass("remove");$("#applyCoupon").addClass("apply");}});$(document).on("focusout","#buy-bundle",function(data){let bundleObj=new CourseBundle();let emailId=$("#userEmail").val();bundleObj.validateField('#userEmail');let isValidated=$("#userEmail").data("validated");let loggedState=$("#userEmail").data("loggedState");let isRegistered=$("#userEmail").data("registeredUser");let emailValidated=$("#userEmail").data("allFieldValidated");if(!isValidated&&!loggedState){let name=$("#userName").val();if(emailId&&name&&emailValidated){let input={type:"validateUser",emailId:emailId,name:name};input["source"]="Not Set";input["medium"]="Not Set";input["campaign"]="Not Set";if(queries.utm_source!=undefined){input["source"]=queries.utm_source;}
if(queries.utm_medium!=undefined){input["medium"]=queries.utm_medium;}
if(queries.utm_campaign!=undefined){input["campaign"]=queries.utm_campaign;}
input["url"]=url;input["product"]="pygame";authorize.ajax(input,"buyBundle",function(data){$("#userEmail").data("validated",true);data=JSON.parse(data);bundleObj.decideUser(data);});}}
let password=$("#password").val();let confirmPassword=$("#confirmPassword").val();if(!$("#userEmail").data("registeredUser")&&password!=confirmPassword&&password&&confirmPassword){$("#misMatch").prop("hidden",false);$("#nonUserMessage").prop("hidden",true);}
else{$("#misMatch").prop("hidden",true);}});$(document).on("click","#bundlePayment",function(){let payObject=new coursePayment();let bundleObj=new CourseBundle();let isRegistered=$("#userEmail").data("registeredUser");$("#userEmail").data("allFieldValidated",true);bundleObj.validateField("#userName");let userName=$("#userName").val();if($("#userEmail").data("loggedState")){let input={type:"logging",userName:userName};input["source"]="Not Set";input["medium"]="Not Set";input["campaign"]="Not Set";if(queries.utm_source!=undefined){input["source"]=queries.utm_source;}
if(queries.utm_medium!=undefined){input["medium"]=queries.utm_medium;}
if(queries.utm_campaign!=undefined){input["campaign"]=queries.utm_campaign;}
input["url"]=url;input["product"]="pygame";if($("#userEmail").data("allFieldValidated")){authorize.ajax(input,"buyBundle",function(data){payObject.paymentTypeRazorPay("pygame_english","courseBundle","",data.auth);});}}
bundleObj.validateField("#password");bundleObj.validateField("#userEmail");let password=$("#password").val();let emailId=$("#userEmail").val();let confirmPassword=$("#confirmPassword").val();if(!isRegistered&&!$("#userEmail").data("loggedState")){if(password!=confirmPassword){$("#userEmail").data("allFieldValidated",false);}
if(password==""){$("#userEmail").data("allFieldValidated",false);}
let input={type:"logging",email:emailId,password:password,fname:userName,lname:""};if($("#userEmail").data("allFieldValidated")){input["source"]="Not Set";input["medium"]="Not Set";input["campaign"]="Not Set";if(queries.utm_source!=undefined){input["source"]=queries.utm_source;}
if(queries.utm_medium!=undefined){input["medium"]=queries.utm_medium;}
if(queries.utm_campaign!=undefined){input["campaign"]=queries.utm_campaign;}
input["url"]=url;grecaptcha.execute("6LdADb4UAAAAAA1feb36sozffPYRKKOqD9WPbibp",{action:"register"}).then(function(token){capchetoken=token;});input["capchetoken"]=capchetoken;authorize.ajax(input,"mregister",function(data){data=data.substring(1,data.length-1)
data=JSON.parse(data);hash=data.hash
input["emails"]=emailId;input["userName"]=userName;input["product"]="pygame";authorize.ajax(input,"buyBundle",function(data){payObject.paymentTypeRazorPay("pygame_english","courseBundle","","",hash);});});}}
let input={type:"login",emails:emailId,password:password,userName:userName};if(isRegistered&&!$("#userEmail").data("loggedState")&&$("#userEmail").data("allFieldValidated")){input["source"]="Not Set";input["medium"]="Not Set";input["campaign"]="Not Set";if(queries.utm_source!=undefined){input["source"]=queries.utm_source;}
if(queries.utm_medium!=undefined){input["medium"]=queries.utm_medium;}
if(queries.utm_campaign!=undefined){input["campaign"]=queries.utm_campaign;}
input["url"]=url;input["product"]="pygame";authorize.ajax(input,"buyBundle",function(data){data=JSON.parse(data);bundleObj.hideProp("#userMessage");if(data.access=="true"){if(data.auth){authorize.setSession("signInAuth",data.auth);}
bundleObj.hideProp("#userMessage");bundleObj.hideProp("#invalidPassword");let payObject=new coursePayment();let authToken=authorize.getSession("signInAuth");payObject.paymentTypeRazorPay("pygame_english","courseBundle","",data.auth);}
else if(data.access=="false"){bundleObj.hideProp("#loginSuccessful");bundleObj.showProp("#invalidPassword");}});}});$(document).on("click","#preview",function(data){let content='<div class="embed-responsive embed-responsive-21by9 video-wrap"><video class="embed-responsive-item" id="sampleVideo"></video></div>';let width="100%";if(window.innerWidth>500){width="50%";}
let video=$(this).data("src");var myModal=new jBox('Modal',{content:content,width:width,onCreated:function(){const customPlayer=new Plyr("#sampleVideo");window.customPlayer=customPlayer;let courseObj=new CourseBundle();courseObj.renderCustomVideo("",video);$(".video-wrap").css("margin",0);$(".jBox-content").css("padding",0);},onCloseComplete:function(){customPlayer.pause();}});myModal.open();});$(document).on("","#buy-bundle",function(data){try{data.preventDefault();$("#userEmail").data("allFieldValidated",true);let bundleObj=new CourseBundle();bundleObj.validateField("#password");let isRegistered=$("#userEmail").data("registeredUser");if(!isRegistered){bundleObj.validateField("#confirmPassword");}
if($("#userEmail").data("allFieldValidated")&&!isRegistered){let firstName=$("#userName").val();let email=$("#userEmail").val();let password=$("#password").val();let input={email:email,password:password,fname:firstName,lname:""};authorize.ajax(input,"mregister",function(data){});}}
catch(error){}});$(document).on("input change","#userEmail",function(data){$("#userEmail").data("validated",false);});$(document).on('click','.is-invalid',function(){$(this).removeClass("is-invalid");});function pygameActivate(mail){authorize.ajax({"type":"onload","mail":mail,"ckey":"pygame_english"},'pygameActivate',function(data){auth=authorize.getSession("authToken");data=JSON.parse(data);if(auth){$("#modal-msg").attr("href","courses.html");$("#modal-msg").text("Go to courses");}
if(data.status=="already activated"){$(".modal-body").text("Course has been already activated!");}else if(data.status=="activated"){$(".modal-body").text("Course activated successfully");}
$("#test").modal('show');});}