$(document).ready(function(){rewardsPage.init();var auth_check=localStorage.getItem("authToken");authorize.ajax({type:"displayContent"},"rewards",function(data){if(data){data=JSON.parse(data);for(var i=0;i<data.length;i++){if(data[i]["rewardType"]=="Run-count"){$(".tests-list").append('<div class="col-sm-12 col-md-12 col-lg-6 col-xl-4 tag  "><div class="card rewards-card shadow-sm"><img class="card-img-top" src="images/Run-count-'+data[i]["reward"]+'.jpg" alt="Card image cap"><div class="card-body verticalCenter"><span class="card-text"><i class="icon-geekoin-big" aria-hidden="true">geekoin:</i>'+data[i]["points"]+'</span><button type="button" class="btn btn-primary float-right redeem" data-toggle="modal" data-target="" data-type="'+data[i]["rewardType"]+'" data-run="'+data[i]["reward"]+'" data-points="'+data[i]["points"]+'" data-id="'+data[i]["activityId"]+'" >Redeem</button></div></div></div>');}
else if(data[i]["rewardType"]=="Course"){$(".tests-list").append('<div class="col-md-12 col-lg-6 col-xl-4 tag  "> <div class="card course-card"> <div class="card-header d-flex flex-row"> <div class=" course-banner '+authorize.getCourseImage(data[i]["reward"])+'"></div> </div> <div class="card-body"> <h5 class="card-title course-title">'+data[i]["course_key"]["name"]+'</h5><ul class="list-unstyled course-highlights"> <li class="lesson-count">'+data[i]["course_key"]["lesson-count"]+' Exclusive Lessons</li> <li class="course-duration">'+data[i]["course_key"]["duration"]+' hrs</li> <li class="proficiency">'+data[i]["course_key"]["lang"]+'</li> </ul><div class="d-flex justify-content-between"> </div><span class="card-text"><i class="icon-geekoin-big" aria-hidden="true">geekoin:</i>'+data[i]["points"]+'</span><div class="d-flex justify-content-end"> <button type="button" class="btn btn-primary float-right courseBuy redeem" data-coursekey="'+data[i]["reward"]+'" data-points="'+data[i]["points"]+'" data-coursename="'+data[i]["course_key"]["name"]+'" data-type="'+data[i]["rewardType"]+'">Redeem</button></div> <a href="courses-product.html?course='+data[i]["reward"]+'&itm_source=rewards_page&itm_medium=click" class="btn pl-0 more-details">Course details</a></div> </div> </div>');}}
if(!auth_check){$(".tests-list button").addClass("navigationLink");}else{$(".tests-list button").removeClass("navigationLink");}}});});var points,activity_id,run_count,course,courseKey;$("div").on("click",".redeem",function(){if(localStorage.getItem("authToken")){$("#rewardsRedeemModal").modal("show");}
$(".modal-content").removeClass("redemption-completed");$(".modal-content").removeClass("redemption-incompleted");if($(this).data("type")=="Run-count"){points=$(this).data("points");activity_id=$(this).data("id");run_count=$(this).data("run");$(".rewardBtn").attr("id","getReward");$("#modal_content").html("<h5>Get "+
run_count+
" Codekata run count.</h5><p>Redeem CodeKata run counts for your geekoins.</p>");$("#modal-body").html("<h5>Yaay! Coupon Redeemed.</h5><p>Run count has been credited to your account.</p>");}else if($(this).data("type")=="Course"){points=$(this).data("points");course=$(this).data("coursename");courseKey=$(this).data("coursekey");$(".rewardBtn").attr("id","getCourse");$("#modal_content").html("<h5>Get "+
course+
" Course.</h5><p>Redeem Courses for your geekoins.</p>");$("#modal-body").html("<h5>Yaay! Course Activated.</h5>");}});$(".modal").on("click","#getReward",function(){json_value={activity_id:activity_id,type:"runCount"};authorize.invisibleAjax(json_value,"rewards",function(data){if(data!="Insufficient geek coins"){$(".complete-redemption").html("<h5>Yaay! Coupon Redeemed.</h5><p>Run count has been credited to your account.</p>");$(".modal-content").addClass("redemption-completed");localStorage.setItem("userpoints",data);authorize.loginCheck();}else{$(".complete-redemption").html("<h5>Oops!</h5><p>Insufficient points to redeem run counts.</p>");$(".modal-content").addClass("redemption-incompleted");$(".modal-content").addClass("redemption-incompleted redemption-completed");}
$(".modal-content").removeClass("loading");});});$(".modal").on("click","#getCourse",function(){json_value={courseName:courseKey};authorize.invisibleAjax(json_value,"courseActivatebyPoints",function(data){data=JSON.parse(data);if(data["status"]!="false"){$(".complete-redemption").html("<h5>Yaay! Coupon Redeemed.</h5><p>Course has been successfully activated.</p>");$(".modal-content").addClass("redemption-completed");var temp=localStorage.getItem("userpoints");localStorage.setItem("userpoints",data["points"]);authorize.loginCheck();}else{$(".complete-redemption").html("<h5>Oops!</h5><p>"+data["message"]+"</p>");$(".modal-content").addClass("redemption-incompleted");$(".modal-content").addClass("redemption-incompleted redemption-completed");}
$(".modal-content").removeClass("loading");});});